HISTSIZE=100000
SAVEHIST=100000

mkdir -p "${HISTFILE:h}"

setopt SHARE_HISTORY
setopt HIST_FCNTL_LOCK
setopt EXTENDED_HISTORY
setopt APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
unsetopt HIST_EXPIRE_DUPS_FIRST
