set -g default-terminal "tmux-256color"
set -g terminal-overrides ',xterm-256color:RGB'

set -g mouse on
setw -g mode-keys vi

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g status-keys emacs
set -g focus-events on
setw -g aggressive-resize on

set -g prefix C-a
bind C-a send-prefix

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Source config
bind r run-shell "tmux source-file \${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf; tmux display-message 'Sourced tmux.conf!'"

# Clear pane output
bind -n C-x send-keys -R \; clear-history
bind l send-keys -R \; clear-history

# Keep layout, equalize pane sizes
set-hook -g after-split-window 'select-layout -E'
set-hook -g pane-exited 'select-layout -E'
set-hook -g after-kill-pane 'select-layout -E'

# Hyprland instance signature
set-hook -g client-attached 'run-shell "tmux set-environment -g HYPRLAND_INSTANCE_SIGNATURE $(ls /tmp/hypr | head -n1)"'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @smooth-scroll-speed "25"

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-processes 'make "log*" k9s btop lazydocker opencode nvim'

# Fork for fixing this issue:
set -g @plugin 'jerek/catppuccin-tmux-fixed-transparency#transparent-status-background-support'
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_background "none"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag, 󰁌 ,}"
set -g @catppuccin_window_text " #W"

set -g status-position top
set -g status-left-length 100
set -g status-right-length 100

set -g status-left "#{E:@catppuccin_status_session} "

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right " #{E:@catppuccin_status_date_time}"
set -g @catppuccin_date_time_text " %H:%M"

run '~/.local/share/tmux/plugins/tpm/tpm'

# Enable OSC 52 clipboard forwarding for remote Neovim yanks.
set -as terminal-features ",*:clipboard"
